<?php


namespace App\Filter;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Lexik\Bundle\FormFilterBundle\Filter\Form\Type as Filters;

class DataFlowCollaboratorFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setMethod('GET');
        $builder->add('collaborators', Filters\ChoiceFilterType::class, [
            'choices' => [
                'All flows' => '*',
                'My flows' => '123',
            ]
        ]);
    }

    public function getBlockPrefix()
    {
        return 'data_flow_collaborator_filter';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}
