fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    resetting:
        form:
            type: App\Form\ResettingPasswordType
    from_email:
        address: "test@domain.com"
        sender_name: "test@domain.com"
