twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    date:
        timezone: '%env(DISPLAY_TIMEZONE)%'
    form_themes:
        - 'form/custom_types.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'bootstrap_4_layout.html.twig'
    globals:
        site_name: '%site_name%'
        site_logo_path: '%site_logo_path%'
        bugherd_apikey: '%bugherd_apikey%'
        user_guide:
            url: '%env(USER_GUIDE_URL)%'
            menu_title: '%env(USER_GUIDE_MENU_TITLE)%'
