twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/custom_types.html.twig'
        - 'bootstrap_4_layout.html.twig'
    globals:
        site_name: '%site_name%'
        site_logo_path: '%site_logo_path%'
